FROM python:3.13

WORKDIR /app

COPY testData/ /app/testData

COPY src/Ingest.py .
COPY .env .

RUN pip install requests python-dotenv beautifulsoup4

#CMD ["python", "Ingest.py"]
CMD ["python", "Ingest.py", "--testData", "--sleep=10"]
