FROM python:3.13

WORKDIR /app

COPY docker/delayStart.sh .
COPY src/UiMgmt.py .
COPY .env .

RUN pip install streamlit python-dotenv

EXPOSE 8501

CMD ["./delayStart.sh", "streamlit", "run", "UiMgmt.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
